name: recsys_stability
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.12
  - numpy=1.26.4 # Numpy 2.0 is not compatible with RecBole
  - pandas=2.3.3
  - scipy=1.16.3
  - scikit-learn=1.7.2
  - matplotlib
  - tqdm
  - pyyaml=6.0.3
  - pandarallel
  
  # NLP
  - gensim=4.4.0
  - spacy=3.8.11
  - transformers=4.57.3
  - nltk=3.9.2
  
  # Deep Learning
  - pytorch=2.6.0
  - torchvision=0.20.1
  - torchaudio=2.6.0

  # Dev
  - ipykernel
  - black
  
  # Pip
  - pip
  - pip:
    - recbole==1.2.0 # 1.2.1 gives an error when trying to install dependencies
    - filelock>=3.0.0 # For Slurm
    # Norwegian Spacy model
    - https://github.com/explosion/spacy-models/releases/download/nb_core_news_md-3.8.0/nb_core_news_md-3.8.0-py3-none-any.whl 
    # English Spacy model
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl
    # Danish Spacy model
    - https://github.com/explosion/spacy-models/releases/download/da_core_news_sm-3.8.0/da_core_news_sm-3.8.0-py3-none-any.whl

    # Not used at all, but required as RecBole forces you to install dependencies for other modules
    - kmeans-pytorch==0.3

    # Used for SBERT
    - sentence-transformers

    - peft
