# FastText Model Configuration

# User representation
aggregation: mean  # Options: mean, sum, max

# Similarity function
similarity: cosine  # Options: cosine, dot

# Embedding configuration
fasttext_dim: 300
embedding_source: fasttext
embedding_path: ~/fasttext/cc.da.300.bin
fasttext_cache: ~/fasttext/cache/cc.da.300.bin.kv
# embedding_path: ~/fasttext/cc.en.300.bin
# fasttext_cache: ~/fasttext/cache/cc.en.300.bin.kv

# Non-trainable model
epochs: 0
