# MIND Small Dataset Configuration

# Field definitions
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: label
TIME_FIELD: timestamp

# Data loading
load_col:
  inter: [user_id, item_id, label, timestamp, impression_id]
  item: [item_id, category, sub_category, title, abstract]

# use pre-generated splits from ETL
benchmark_filename: ['train', 'valid', 'test']

# Filtering (Within each window, we only retain users and items with interactions)
user_inter_num_interval: "[1,inf)"
item_inter_num_interval: "[0,inf)"
filter_inter_by_user_or_item: true

eval_args:
  split: {'LS': 'valid_and_test'}
  group_by: user
  order: TO
  mode: {'valid': 'uni4', 'test': 'uni4'}


# Metrics
metrics: ['Recall', 'NDCG', 'Hit', 'Precision', 'MRR', 'GAUC']
topk: [1, 5, 10]
valid_metric: NDCG@10
