title_field: title
title_len: 30

seq_len:
  title: 30
  history_item_id_list: 50

# hyper params (from paper)
word_embedding_dim: 300
num_heads: 16
head_dim: 16 # output per head
att_dim: 200 # additive attention hidden/query dim
emb_dropout: 0.2

# Used for training
neg_sample_num: 4

# Training (from paper)
optimizer: Adam
learning_rate: 0.001   # paper says Adam; LR tuned on validation; start here
train_batch_size: 64

freeze_embeddings: true
embedding_source: "glove"
embedding_path: "data/glove.6B.300d.txt"



# Custom eval args (needed for custom data loader)
eval_neg_sample_num: # Use full (up to max) impressions for evaluation
eval_max_neg_sample_num:
  # Percentiles for MIND: p25=12, p50=31, p75=65, p90=104, p95=128, p99=197
  val: 104 # Should cover about the 90% percentile of all negative impressions
  test: # Use full impressions for test
eval_shuffle_within_impression: false # We want deterministic evaluation, and no need to shuffle




# Needed for sequential models
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: null

# Uses custom impression based negative sampling
# train_neg_sample_args:
#   distribution: uniform
#   sample_num: 4


shuffle_within_impression: true

enable_amp: true
enable_scaler: true

stopping_step: 5

