# Random Model Configuration
# Non-trainable baseline - ranks items randomly

# Non-trainable
epochs: 0

eval_max_neg_sample_num:
  val: 5 
  test: 5 # Cap at 10 negatives per positive

# Keep only impressions with at least 10 negatives so that
# the instability in results are less dependent on size of negatives.
# Should be used together with the eval_max_neg_sample num setting.
impression_negatives_num_interval:
  train:
  val: "[5,inf)"
  test: "[5,inf)"
