# SBERT-based model configuration

# Non-trainable model
epochs: 0

eval_max_neg_sample_num:
  val: 9 
  test: 9 # Cap at 9 negatives per positive

# Keep only impressions with at least 9 negatives so that
# the instability in results are less dependent on size of negatives.
# Should be used together with the eval_max_neg_sample num setting.
impression_negatives_num_interval:
  train:
  val: "[9,inf)"
  test: "[9,inf)"


sentence_embedding_model: sentence-transformers/distiluse-base-multilingual-cased-v2
sentence_embedding_dim: 512 # This needs to match the output of the model defined above